# Generated by Django 4.1.9 on 2023-10-31 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotation_item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='quotation_items',
            field=models.ManyToManyField(blank=True, to='quotation_item.quotationitem'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
