# Generated by Django 4.1.9 on 2023-12-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_offer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='special_offers/'),
        ),
    ]
