# Generated by Django 4.1.9 on 2023-11-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0002_alter_testimonial_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='testimonial/'),
        ),
    ]
