# Generated by Django 4.1.9 on 2023-10-31 09:38

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='product_brands')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=400)),
                ('display_order', models.SmallIntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Product Brands',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductCoupon',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=200, unique=True)),
                ('value', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, max_length=400)),
                ('type', models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], default='fixed', max_length=100)),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Product Coupons',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='product_tags')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=400)),
                ('display_order', models.SmallIntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Product Tags',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='product_categories')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=400)),
                ('display_order', models.SmallIntegerField(blank=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productcategory')),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='product_categories')),
                ('description', models.TextField(blank=True, max_length=400)),
                ('details', ckeditor.fields.RichTextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_favourite', models.BooleanField(default=False)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, max_length=5, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productbrand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productcategory')),
                ('related_products', models.ManyToManyField(blank=True, to='product.product')),
            ],
        ),
    ]
