# Generated by Django 4.1.9 on 2023-10-31 19:30

from django.db import migrations, models
import product.category.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
            ],
            options={
                'verbose_name_plural': 'SubCategories',
                'db_table': 'product_ProductCategory',
                'managed': False,
                'proxy': product.category.models.ProductCategory,
                'auto_created': False,
            },
            bases=('product.productcategory',),
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product Categories'},
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='parent_category',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='priority',
            field=models.IntegerField(default=0, help_text='Enter priority list order by lowest to highest. 0 is at the start of the list'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='sub_category',
            field=models.ManyToManyField(blank=True, to='product.productcategory'),
        ),
    ]
