# Generated by Django 4.1.9 on 2023-10-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BioData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', models.EmailField(max_length=254)),
                ('phone_numbers', models.CharField(max_length=15)),
                ('sales_email', models.EmailField(max_length=254)),
                ('contact_us_email', models.EmailField(max_length=254)),
                ('footer_text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Bio Data',
            },
        ),
    ]
