"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.1.9.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
import sys
from pathlib import Path
from django.contrib import messages
from datetime import timedelta
from django.utils.functional import LazyObject, empty
from dotenv import load_dotenv
from pathlib import Path

sys.path.append(os.path.realpath('.'))


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(os.path.join(BASE_DIR,".env") )

ONLY_ADMIN = os.getenv('ONLY_ADMIN', 'off') == 'on'
SECRET_KEY = os.getenv("SECRET_KEY", "1234")
ABS_PATH=os.path.join(os.path.dirname(os.path.abspath(__file__)),"..")
DEBUG = os.getenv("DJANGO_DEBUG") != "False"
TEMPLATES_DIR = os.path.join(BASE_DIR, "templates")
STATICFILES_DIR = os.path.join(BASE_DIR, "staticfiles")
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_DIR = os.path.join(BASE_DIR, "static")
MEDIA_DIR = os.path.join(BASE_DIR, "media")
LOGS_DIR = os.path.join(BASE_DIR, "logs")
AWS_ACCESS_KEY_ID = 'your-access-key-id'
AWS_SECRET_ACCESS_KEY = 'your-secret-access-key'
AWS_STORAGE_BUCKET_NAME = 'your-bucket-name'
AWS_S3_REGION_NAME = 'your-region-name'
DEFAULT_FILE_STORAGE = 'path.to.S3Storage'
DEFAULT_APP_URL = os.getenv('DEFAULT_APP_URL')
DEFAULT_API_URL = os.getenv('DEFAULT_API_URL')
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "1234")
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!


# SECURITY WARNING: don't run with debug turned on in production!

class MyTokenObtainPairViewLazy(LazyObject):
    def _setup(self):
        from accounts.views import MyTokenObtainPairView
        self._wrapped = MyTokenObtainPairView()

MyTokenObtainPairView = MyTokenObtainPairViewLazy

DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'admin_volt.apps.AdminVoltConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    

    
    
    
    "rest_framework.authtoken",
    "rest_framework_simplejwt",
    "drf_yasg",
    "accounts",
    'rest_framework',
    'rest_framework_swagger',
    'djoser',
    'blog',
    'contact_us',
    'testimonial',
    'product',
    'special_offer',
    'hero',
    'biodata',
    'user',
    'userprofile',
    'quotation',
    'quotation_item',
    'order',
    
]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',

]


ROOT_URLCONF = 'core.urls'

DJOSER = {
    'SEND_ACTIVATION_EMAIL': False,
    'SEND_CONFIRMATION_EMAIL': False,
    'PASSWORD_CHANGED_EMAIL_CONFIRMATION': False,
    'USERNAME_CHANGED_EMAIL_CONFIRMATION': False,
    'ACTIVATION_URL':'auth/activation/{uid}/{token}', #change to Frontend url
    'PASSWORD_RESET_CONFIRM_URL': 'auth/password-reset/{uid}/{token}', #change to Frontend url
    'LOGOUT_ON_PASSWORD_CHANGE': False,
    'SERIALIZERS': {
        'user_create': 'accounts.serializers.UserCreateSerializer',
        'current_user': 'accounts.serializers.UserSerializer',
    },
    'EMAIL':{
     'password_reset':'accounts.views.PasswordResetEmail'
    }
}

SIMPLE_JWT = {
    'AUTH_HEADER_TYPES': ('JWT', 'Bearer'),
    'ACCESS_TOKEN_LIFETIME': timedelta(days=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=5),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,

    # use the custom token serializer
    'TOKEN_SERIALIZER': MyTokenObtainPairView,

    # add the custom claims to the token
    'CLAIMS': {
        'name': 'auth.name',
        'role': 'auth.role',
        'email': 'auth.email',
        'is_staff': 'auth.is_staff',
        'username' : 'auth.username'
    },
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache',
        'LOCATION': '127.0.0.1:11211',
    }
}

STATIC_URL = '/static/'
LOGIN_REDIRECT_URL = '/'
LOGIN_URL = 'auth/login/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') 	#MEDIA_DIR
FILE_UPLOAD_MAX_MEMORY_SIZE = 20971520
# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



# Register User model in admin
REGISTER_USER_MODEL = True

# Custom user model
AUTH_USER_MODEL = 'accounts.user'
#DATABASES['default'] = dj_database_url.parse('postgres://keep_am_here_user:vXkPFacXcUG74lA9x7oiqk5RGNjjCOls@dpg-cjfse5hitvpc73dgi5h0-a.oregon-postgres.render.com/keep_am_here')

AUTH_PASSWORD_VALIDATORS = [    {        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',    },    {        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',    },]


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


EMAIL_BACKEND= 'anymail.backends.sendgrid.EmailBackend'
DEFAULT_FROM_EMAIL = 'mokwenyekene1@yahoo.com'