# Generated by Django 4.1.9 on 2023-10-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header', models.TextField()),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='hero_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
