# Generated by Django 4.1.9 on 2023-11-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='phone_numbers',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
