# Generated by Django 4.1.9 on 2023-11-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_hero_phone_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='content',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
