# Generated by Django 4.1.9 on 2023-11-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_hero_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='content',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hero_images/'),
        ),
    ]
